import { Request, Response } from "express";
import { AuthorizationCode } from "simple-oauth2";
import dotenv from "dotenv";
import fetch from "node-fetch";
import { execSync } from "child_process";
import path from "path";
import fs from "fs";

dotenv.config();

export let quickBooksToken: any = null;
export let quickBooksRealmId: string | null = null;

const client = new AuthorizationCode({
  client: {
    id: process.env.QUICKBOOKS_CLIENT_ID!,
    secret: process.env.QUICKBOOKS_CLIENT_SECRET!,
  },
  auth: {
    tokenHost: "https://oauth.platform.intuit.com",
    authorizeHost: "https://appcenter.intuit.com",
    authorizePath: "/connect/oauth2",
    tokenPath: "/oauth2/v1/tokens/bearer",
  },
});


// Step 1: OAuth
export const startOAuth = (req: Request, res: Response) => {
  console.log("[QuickBooks Service] startOAuth called");
  const authorizationUri = client.authorizeURL({
    redirect_uri: process.env.CALLBACK_URL!,
    scope: "com.intuit.quickbooks.accounting",
    state: Math.random().toString(36).substring(7),
  });
  console.log("[QuickBooks Service] Redirecting to:", authorizationUri);
  res.redirect(authorizationUri);
};

// Step 2: OAuth callback
export const quickbooksCallback = async (req: Request, res: Response) => {
  console.log("[QuickBooks Service] quickbooksCallback called with query:", req.query);
  const { code, realmId } = req.query;
  try {
    const accessToken = await client.getToken({
      code: code as string,
      redirect_uri: process.env.CALLBACK_URL!,
      scope: "com.intuit.quickbooks.accounting",
    });

    quickBooksToken = accessToken.token;
    quickBooksRealmId = realmId as string;
    console.log("[QuickBooks Service] QuickBooks token saved:", quickBooksToken, "RealmId:", quickBooksRealmId);

    res.send(`
      <h2>QuickBooks Connected!</h2>
      <p>You may now close this tab and return to the app.</p>
    `);
  } catch (error) {
    console.error("[QuickBooks Service] OAuth Callback Error", error);
    res.status(500).send("OAuth callback error: " + (error as any).message);
  }
};

// Step 3: ZK proof (with QuickBooks)
export const proveReliabilityWithQuickbooks = async (req: Request, res: Response) => {
  console.log("[QuickBooks Service] proveReliabilityWithQuickbooks called with body:", req.body);

  const { threshold_percent } = req.body;
  if (!quickBooksToken || !quickBooksRealmId) {
    console.warn("[QuickBooks Service] Not connected to QuickBooks. Token or realmId missing.");
    return res.status(401).json({ error: "QuickBooks not connected." });
  }

  const url = `https://quickbooks.api.intuit.com/v3/company/${quickBooksRealmId}/query?query=SELECT%20*%20FROM%20Invoice`;
  const accessToken = quickBooksToken.access_token;

  let total = 0, paid = 0;
  try {
    console.log("[QuickBooks Service] Fetching invoices from:", url);
    const qbRes = await fetch(url, {
      method: "GET",
      headers: {
        "Authorization": `Bearer ${accessToken}`,
        "Accept": "application/json",
        "Content-Type": "application/text",
      }
    });
    if (!qbRes.ok) throw new Error("QB fetch failed");
    const qbData = await qbRes.json() as any;
    const invoices = qbData.QueryResponse.Invoice || [];
    total = invoices.length;
    paid = invoices.filter((inv: any) => Number(inv.Balance) === 0).length;
    console.log(`[QuickBooks Service] Invoice counts: total=${total}, paid=${paid}`);
  } catch (err) {
    console.error("[QuickBooks Service] QuickBooks fetch error:", err);
    return res.status(500).json({ error: "Failed to fetch invoices from QuickBooks" });
  }

  // Write TOML for Noir
  const toml = `total_invoices = ${total}\npaid_invoices = ${paid}\nthreshold_percent = ${threshold_percent}\n`;
  const proverPath = path.join(__dirname, "../../invoice_reliability/Prover.toml");
  console.log(`[QuickBooks Service] Writing TOML to ${proverPath}:\n${toml}`);
  fs.writeFileSync(proverPath, toml);

  try {
    console.log("[QuickBooks Service] Executing: nargo execute");
    const result = execSync('nargo execute', {
      cwd: path.join(__dirname, "../../invoice_reliability"),
    }).toString();
    console.log("[QuickBooks Service] nargo output:", result);

    const match = result.match(/Field\((\d)\)/);
    const isReliable = match ? match[1] === '1' : false;

    res.json({
      zk_proof: "Proof generated by Noir",
      isReliable,
      threshold_percent,
    });
  } catch (e) {
    let msg = "Unknown error";
    let nargoOutput = undefined;
    if (e instanceof Error) {
      msg = e.message;
      // @ts-ignore
      nargoOutput = (e as any).stdout?.toString();
    } else if (typeof e === "string") {
      msg = e;
    }
    console.error("[QuickBooks Service] nargo execute error:", msg, nargoOutput);
    res.status(500).json({ error: msg, nargoOutput });
  }




  
};
